---
- hosts: jenkins
  become: true
  tasks:
    - name: Update cache & Full system update
      apt:
        update_cache: true
        force_apt_get: true
    - name: raw
      raw: docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts-jdk11