---
- hosts: web
  become: true
  tasks:
    - name: Update cache & Full system update
      apt:
        update_cache: true
        force_apt_get: true
    - name: raw
      raw: docker run -d -h apache2 --name apache2 -p 80:80 -p 443:443 -v apache2volume:/var/www/html sismics/apache2
